2025-02-17 21:48:21,969 - INFO - Starting Flask server...
2025-02-17 21:48:22,047 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 21:48:22,047 - ERROR -   warnings.warn(
2025-02-17 21:48:22,050 - INFO - b" * Serving Flask app 'app'"
2025-02-17 21:48:22,050 - INFO - b' * Debug mode: on'
2025-02-17 21:48:22,073 - ERROR - Traceback (most recent call last):
2025-02-17 21:48:22,074 - ERROR -   File "C:\Dev\Web Apps\VM_WEB_GUI\app.py", line 202, in <module>
2025-02-17 21:48:22,074 - ERROR -     app.run(host="0.0.0.0",
2025-02-17 21:48:22,074 - ERROR -     ~~~~~~~^^^^^^^^^^^^^^^^
2025-02-17 21:48:22,074 - ERROR -             ssl_context=("/mnt/wsl/Ubuntu/etc/letsencrypt/live/zamatallica.ddns.net/fullchain.pem",
2025-02-17 21:48:22,074 - ERROR -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:22,074 - ERROR -                         "/mnt/wsl/Ubuntu/etc/letsencrypt/live/zamatallica.ddns.net/privkey.pem"),
2025-02-17 21:48:22,074 - ERROR -                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:22,074 - ERROR -             port=443, debug=True)
2025-02-17 21:48:22,074 - ERROR -             ^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:22,074 - ERROR -   File "C:\Python313\Lib\site-packages\flask\app.py", line 662, in run
2025-02-17 21:48:22,075 - ERROR -     run_simple(t.cast(str, host), port, self, **options)
2025-02-17 21:48:22,075 - ERROR -     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:22,075 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 1093, in run_simple
2025-02-17 21:48:22,075 - ERROR -     srv = make_server(
2025-02-17 21:48:22,075 - ERROR -         hostname,
2025-02-17 21:48:22,075 - ERROR -     ...<7 lines>...
2025-02-17 21:48:22,075 - ERROR -         fd=fd,
2025-02-17 21:48:22,075 - ERROR -     )
2025-02-17 21:48:22,075 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 930, in make_server
2025-02-17 21:48:22,075 - ERROR -     return ThreadedWSGIServer(
2025-02-17 21:48:22,075 - ERROR -         host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
2025-02-17 21:48:22,075 - ERROR -     )
2025-02-17 21:48:22,075 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 801, in __init__
2025-02-17 21:48:22,075 - ERROR -     ssl_context = load_ssl_context(*ssl_context)
2025-02-17 21:48:22,075 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 644, in load_ssl_context
2025-02-17 21:48:22,075 - ERROR -     ctx.load_cert_chain(cert_file, pkey_file)
2025-02-17 21:48:22,075 - ERROR -     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:22,076 - ERROR - FileNotFoundError: [Errno 2] No such file or directory
2025-02-17 21:48:44,350 - INFO - Starting Flask server...
2025-02-17 21:48:44,419 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 21:48:44,419 - ERROR -   warnings.warn(
2025-02-17 21:48:44,421 - INFO - b" * Serving Flask app 'app'"
2025-02-17 21:48:44,421 - INFO - b' * Debug mode: on'
2025-02-17 21:48:44,443 - ERROR - Traceback (most recent call last):
2025-02-17 21:48:44,444 - ERROR -   File "C:\Dev\Web Apps\VM_WEB_GUI\app.py", line 202, in <module>
2025-02-17 21:48:44,444 - ERROR -     app.run(host="0.0.0.0",
2025-02-17 21:48:44,444 - ERROR -     ~~~~~~~^^^^^^^^^^^^^^^^
2025-02-17 21:48:44,444 - ERROR -             ssl_context=("/mnt/wsl/Ubuntu/etc/letsencrypt/live/zamatallica.ddns.net/fullchain.pem",
2025-02-17 21:48:44,444 - ERROR -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:44,444 - ERROR -                         "/mnt/wsl/Ubuntu/etc/letsencrypt/live/zamatallica.ddns.net/privkey.pem"),
2025-02-17 21:48:44,444 - ERROR -                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:44,444 - ERROR -             port=443, debug=True)
2025-02-17 21:48:44,444 - ERROR -             ^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:44,444 - ERROR -   File "C:\Python313\Lib\site-packages\flask\app.py", line 662, in run
2025-02-17 21:48:44,444 - ERROR -     run_simple(t.cast(str, host), port, self, **options)
2025-02-17 21:48:44,444 - ERROR -     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:44,444 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 1093, in run_simple
2025-02-17 21:48:44,444 - ERROR -     srv = make_server(
2025-02-17 21:48:44,444 - ERROR -         hostname,
2025-02-17 21:48:44,444 - ERROR -     ...<7 lines>...
2025-02-17 21:48:44,444 - ERROR -         fd=fd,
2025-02-17 21:48:44,444 - ERROR -     )
2025-02-17 21:48:44,445 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 930, in make_server
2025-02-17 21:48:44,445 - ERROR -     return ThreadedWSGIServer(
2025-02-17 21:48:44,445 - ERROR -         host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
2025-02-17 21:48:44,445 - ERROR -     )
2025-02-17 21:48:44,445 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 801, in __init__
2025-02-17 21:48:44,445 - ERROR -     ssl_context = load_ssl_context(*ssl_context)
2025-02-17 21:48:44,445 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 644, in load_ssl_context
2025-02-17 21:48:44,445 - ERROR -     ctx.load_cert_chain(cert_file, pkey_file)
2025-02-17 21:48:44,445 - ERROR -     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:44,445 - ERROR - FileNotFoundError: [Errno 2] No such file or directory
2025-02-17 21:48:59,788 - INFO - Starting Flask server...
2025-02-17 21:48:59,860 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 21:48:59,860 - ERROR -   warnings.warn(
2025-02-17 21:48:59,863 - INFO - b" * Serving Flask app 'app'"
2025-02-17 21:48:59,863 - INFO - b' * Debug mode: on'
2025-02-17 21:48:59,885 - ERROR - Traceback (most recent call last):
2025-02-17 21:48:59,886 - ERROR -   File "C:\Dev\Web Apps\VM_WEB_GUI\app.py", line 202, in <module>
2025-02-17 21:48:59,886 - ERROR -     app.run(host="0.0.0.0",
2025-02-17 21:48:59,886 - ERROR -     ~~~~~~~^^^^^^^^^^^^^^^^
2025-02-17 21:48:59,886 - ERROR -             ssl_context=("/mnt/wsl/Ubuntu/etc/letsencrypt/live/zamatallica.ddns.net/fullchain.pem",
2025-02-17 21:48:59,886 - ERROR -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:59,886 - ERROR -                         "/mnt/wsl/Ubuntu/etc/letsencrypt/live/zamatallica.ddns.net/privkey.pem"),
2025-02-17 21:48:59,886 - ERROR -                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:59,886 - ERROR -             port=443, debug=True)
2025-02-17 21:48:59,886 - ERROR -             ^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:59,886 - ERROR -   File "C:\Python313\Lib\site-packages\flask\app.py", line 662, in run
2025-02-17 21:48:59,886 - ERROR -     run_simple(t.cast(str, host), port, self, **options)
2025-02-17 21:48:59,886 - ERROR -     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:59,886 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 1093, in run_simple
2025-02-17 21:48:59,886 - ERROR -     srv = make_server(
2025-02-17 21:48:59,886 - ERROR -         hostname,
2025-02-17 21:48:59,886 - ERROR -     ...<7 lines>...
2025-02-17 21:48:59,887 - ERROR -         fd=fd,
2025-02-17 21:48:59,887 - ERROR -     )
2025-02-17 21:48:59,887 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 930, in make_server
2025-02-17 21:48:59,887 - ERROR -     return ThreadedWSGIServer(
2025-02-17 21:48:59,887 - ERROR -         host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
2025-02-17 21:48:59,887 - ERROR -     )
2025-02-17 21:48:59,887 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 801, in __init__
2025-02-17 21:48:59,887 - ERROR -     ssl_context = load_ssl_context(*ssl_context)
2025-02-17 21:48:59,887 - ERROR -   File "C:\Python313\Lib\site-packages\werkzeug\serving.py", line 644, in load_ssl_context
2025-02-17 21:48:59,887 - ERROR -     ctx.load_cert_chain(cert_file, pkey_file)
2025-02-17 21:48:59,887 - ERROR -     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
2025-02-17 21:48:59,887 - ERROR - FileNotFoundError: [Errno 2] No such file or directory
2025-02-17 22:12:11,742 - INFO - Starting Flask server...
2025-02-17 22:12:11,817 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:12:11,817 - ERROR -   warnings.warn(
2025-02-17 22:12:11,820 - INFO - b" * Serving Flask app 'app'"
2025-02-17 22:12:11,820 - INFO - b' * Debug mode: on'
2025-02-17 22:12:11,886 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:443
 * Running on https://192.168.1.19:443
2025-02-17 22:12:11,887 - INFO - [33mPress CTRL+C to quit[0m
2025-02-17 22:12:11,888 - INFO -  * Restarting with stat
2025-02-17 22:12:12,149 - INFO - Starting Flask server...
2025-02-17 22:12:12,226 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:12:12,226 - ERROR -   warnings.warn(
2025-02-17 22:12:12,241 - WARNING -  * Debugger is active!
2025-02-17 22:12:12,248 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:12:56,803 - INFO - 192.168.1.19 - - [17/Feb/2025 22:12:56] "GET / HTTP/1.1" 200 -
2025-02-17 22:14:01,660 - INFO - 192.168.1.19 - - [17/Feb/2025 22:14:01] "GET / HTTP/1.1" 200 -
2025-02-17 22:14:26,141 - INFO - 192.168.1.19 - - [17/Feb/2025 22:14:26] "GET / HTTP/1.1" 200 -
2025-02-17 22:17:04,665 - INFO - 192.168.1.10 - - [17/Feb/2025 22:17:04] "GET / HTTP/1.1" 200 -
2025-02-17 22:17:04,707 - INFO - 192.168.1.10 - - [17/Feb/2025 22:17:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-02-17 22:21:26,783 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 22:21:26,817 - INFO -  * Restarting with stat
2025-02-17 22:21:27,085 - INFO - Starting Flask server...
2025-02-17 22:21:27,160 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:21:27,160 - ERROR -   warnings.warn(
2025-02-17 22:21:27,175 - WARNING -  * Debugger is active!
2025-02-17 22:21:27,177 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:21:41,629 - INFO - 192.168.1.10 - - [17/Feb/2025 22:21:41] "GET / HTTP/1.1" 200 -
2025-02-17 22:22:10,847 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 22:22:10,885 - INFO -  * Restarting with stat
2025-02-17 22:22:11,157 - INFO - Starting Flask server...
2025-02-17 22:22:11,226 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:22:11,226 - ERROR -   warnings.warn(
2025-02-17 22:22:11,241 - WARNING -  * Debugger is active!
2025-02-17 22:22:11,243 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:22:16,057 - ERROR - 192.168.1.10 - - [17/Feb/2025 22:22:16] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x07¯\x01\x00\x07«\x03\x03~>Cé')
2025-02-17 22:22:16,057 - INFO - 192.168.1.10 - - [17/Feb/2025 22:22:16] "[31m[1m\x16\x03\x01\x07¯\x01\x00\x07«\x03\x03~>Cé\x1e09n"\x81\x1b7téÉ[0m" 400 -
2025-02-17 22:22:16,059 - ERROR - 192.168.1.10 - - [17/Feb/2025 22:22:16] code 400, message Bad request version ('dÕ\x93Í$½[\x8fä\x82\x16\x8fÍJ\x870fA\x00')
2025-02-17 22:22:16,059 - INFO - 192.168.1.10 - - [17/Feb/2025 22:22:16] "[31m[1m\x16\x03\x01\x08\x0f\x01\x00\x08\x0b\x03\x03jR#Ä)Ð!¤k\x09×»øÛË2Ê\x05ÍC6\x04\x0f«0\x84\x02ÂÑ¤\x9eG óyÉh½PÎ\x83Iîå\x19µ\x1edÕ\x93Í$½[\x8fä\x82\x16\x8fÍJ\x870fA\x00 [0m" 400 -
2025-02-17 22:24:38,073 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 22:24:38,105 - INFO -  * Restarting with stat
2025-02-17 22:24:38,394 - INFO - Starting Flask server...
2025-02-17 22:24:38,476 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:24:38,476 - ERROR -   warnings.warn(
2025-02-17 22:24:38,493 - WARNING -  * Debugger is active!
2025-02-17 22:24:38,496 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:24:53,232 - INFO - Starting Flask server...
2025-02-17 22:24:53,306 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:24:53,306 - ERROR -   warnings.warn(
2025-02-17 22:24:53,308 - INFO - b" * Serving Flask app 'app'"
2025-02-17 22:24:53,308 - INFO - b' * Debug mode: on'
2025-02-17 22:24:53,323 - ERROR - An attempt was made to access a socket in a way forbidden by its access permissions
2025-02-17 22:25:07,691 - INFO - Starting Flask server...
2025-02-17 22:25:07,760 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:25:07,760 - ERROR -   warnings.warn(
2025-02-17 22:25:07,762 - INFO - b" * Serving Flask app 'app'"
2025-02-17 22:25:07,763 - INFO - b' * Debug mode: on'
2025-02-17 22:25:07,778 - ERROR - An attempt was made to access a socket in a way forbidden by its access permissions
2025-02-17 22:27:10,517 - INFO - Starting Flask server...
2025-02-17 22:27:10,588 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:27:10,588 - ERROR -   warnings.warn(
2025-02-17 22:27:10,590 - INFO - b" * Serving Flask app 'app'"
2025-02-17 22:27:10,590 - INFO - b' * Debug mode: on'
2025-02-17 22:27:10,613 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.19:5000
2025-02-17 22:27:10,613 - INFO - [33mPress CTRL+C to quit[0m
2025-02-17 22:27:10,614 - INFO -  * Restarting with stat
2025-02-17 22:27:10,862 - INFO - Starting Flask server...
2025-02-17 22:27:10,930 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:27:10,930 - ERROR -   warnings.warn(
2025-02-17 22:27:10,945 - WARNING -  * Debugger is active!
2025-02-17 22:27:10,947 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:28:27,072 - INFO - Starting Flask server...
2025-02-17 22:28:27,144 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:28:27,145 - ERROR -   warnings.warn(
2025-02-17 22:28:27,147 - INFO - b" * Serving Flask app 'app'"
2025-02-17 22:28:27,147 - INFO - b' * Debug mode: on'
2025-02-17 22:28:27,169 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.1.19:5001
2025-02-17 22:28:27,169 - INFO - [33mPress CTRL+C to quit[0m
2025-02-17 22:28:27,170 - INFO -  * Restarting with stat
2025-02-17 22:28:27,433 - INFO - Starting Flask server...
2025-02-17 22:28:27,505 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:28:27,505 - ERROR -   warnings.warn(
2025-02-17 22:28:27,520 - WARNING -  * Debugger is active!
2025-02-17 22:28:27,522 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:29:43,562 - INFO - 192.168.1.10 - - [17/Feb/2025 22:29:43] "GET / HTTP/1.1" 200 -
2025-02-17 22:29:43,628 - INFO - 192.168.1.10 - - [17/Feb/2025 22:29:43] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-02-17 22:31:33,314 - INFO - 192.168.1.10 - - [17/Feb/2025 22:31:33] "GET / HTTP/1.1" 200 -
2025-02-17 22:31:41,431 - DEBUG - Received username: admin, password length: 9
2025-02-17 22:31:41,432 - DEBUG - Attempting to establish database connection...
2025-02-17 22:31:41,639 - DEBUG - Database connection established successfully.
2025-02-17 22:31:41,839 - DEBUG - Incorrect password
2025-02-17 22:31:41,840 - INFO - 192.168.1.10 - - [17/Feb/2025 22:31:41] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:31:49,165 - DEBUG - Received username: admin, password length: 9
2025-02-17 22:31:49,165 - DEBUG - Attempting to establish database connection...
2025-02-17 22:31:49,169 - DEBUG - Database connection established successfully.
2025-02-17 22:31:49,364 - DEBUG - Login successful
2025-02-17 22:31:49,365 - INFO - 192.168.1.10 - - [17/Feb/2025 22:31:49] "POST /api/login HTTP/1.1" 200 -
2025-02-17 22:32:19,501 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 22:32:19,543 - INFO -  * Restarting with stat
2025-02-17 22:32:19,809 - INFO - Starting Flask server...
2025-02-17 22:32:19,885 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:32:19,885 - ERROR -   warnings.warn(
2025-02-17 22:32:19,900 - WARNING -  * Debugger is active!
2025-02-17 22:32:19,902 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:32:21,046 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 22:32:21,079 - INFO -  * Restarting with stat
2025-02-17 22:32:21,350 - INFO - Starting Flask server...
2025-02-17 22:32:21,427 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:32:21,427 - ERROR -   warnings.warn(
2025-02-17 22:32:21,443 - WARNING -  * Debugger is active!
2025-02-17 22:32:21,445 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:33:54,826 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 22:33:54,974 - INFO -  * Restarting with stat
2025-02-17 22:33:55,259 - INFO - Starting Flask server...
2025-02-17 22:33:55,335 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:33:55,335 - ERROR -   warnings.warn(
2025-02-17 22:33:55,350 - WARNING -  * Debugger is active!
2025-02-17 22:33:55,353 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:34:51,046 - INFO - Starting Flask server...
2025-02-17 22:34:51,118 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:34:51,118 - ERROR -   warnings.warn(
2025-02-17 22:34:51,120 - INFO - b" * Serving Flask app 'app'"
2025-02-17 22:34:51,121 - INFO - b' * Debug mode: on'
2025-02-17 22:34:51,145 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:443
 * Running on https://192.168.1.19:443
2025-02-17 22:34:51,145 - INFO - [33mPress CTRL+C to quit[0m
2025-02-17 22:34:51,147 - INFO -  * Restarting with stat
2025-02-17 22:34:51,390 - INFO - Starting Flask server...
2025-02-17 22:34:51,457 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 22:34:51,458 - ERROR -   warnings.warn(
2025-02-17 22:34:51,472 - WARNING -  * Debugger is active!
2025-02-17 22:34:51,474 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 22:35:04,492 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:04] "GET / HTTP/1.1" 200 -
2025-02-17 22:35:11,902 - DEBUG - Received username: admin, password length: 9
2025-02-17 22:35:11,902 - DEBUG - Attempting to establish database connection...
2025-02-17 22:35:11,927 - DEBUG - Database connection established successfully.
2025-02-17 22:35:12,118 - DEBUG - Login successful
2025-02-17 22:35:12,119 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:12] "POST /api/login HTTP/1.1" 200 -
2025-02-17 22:35:14,773 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:14] "GET / HTTP/1.1" 200 -
2025-02-17 22:35:31,013 - DEBUG - Received username: admin, password length: 10
2025-02-17 22:35:31,013 - DEBUG - Attempting to establish database connection...
2025-02-17 22:35:31,018 - DEBUG - Database connection established successfully.
2025-02-17 22:35:31,207 - DEBUG - Incorrect password
2025-02-17 22:35:31,208 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:31] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:35:32,709 - DEBUG - Received username: admin, password length: 14
2025-02-17 22:35:32,709 - DEBUG - Attempting to establish database connection...
2025-02-17 22:35:32,710 - DEBUG - Database connection established successfully.
2025-02-17 22:35:32,901 - DEBUG - Incorrect password
2025-02-17 22:35:32,902 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:32] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:35:34,604 - DEBUG - Received username: admin, password length: 17
2025-02-17 22:35:34,605 - DEBUG - Attempting to establish database connection...
2025-02-17 22:35:34,605 - DEBUG - Database connection established successfully.
2025-02-17 22:35:34,796 - DEBUG - Incorrect password
2025-02-17 22:35:34,797 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:34] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:35:35,821 - DEBUG - Received username: admin, password length: 21
2025-02-17 22:35:35,821 - DEBUG - Attempting to establish database connection...
2025-02-17 22:35:35,822 - DEBUG - Database connection established successfully.
2025-02-17 22:35:36,013 - DEBUG - Incorrect password
2025-02-17 22:35:36,014 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:36] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:35:36,532 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:35:36,533 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:36] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:35:37,509 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:35:37,509 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:37] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:35:38,516 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:35:38,517 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:38] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:35:42,958 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:42] "GET / HTTP/1.1" 200 -
2025-02-17 22:35:48,773 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:35:48,773 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:48] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:35:53,789 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:35:53,789 - INFO - 192.168.1.10 - - [17/Feb/2025 22:35:53] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:39:23,504 - DEBUG - Received username: admin, password length: 9
2025-02-17 22:39:23,505 - DEBUG - Attempting to establish database connection...
2025-02-17 22:39:23,515 - DEBUG - Database connection established successfully.
2025-02-17 22:39:23,706 - DEBUG - Login successful
2025-02-17 22:39:23,708 - INFO - 192.168.1.10 - - [17/Feb/2025 22:39:23] "POST /api/login HTTP/1.1" 200 -
2025-02-17 22:39:27,012 - INFO - 192.168.1.10 - - [17/Feb/2025 22:39:27] "GET / HTTP/1.1" 200 -
2025-02-17 22:39:28,968 - INFO - 192.168.1.10 - - [17/Feb/2025 22:39:28] "GET / HTTP/1.1" 200 -
2025-02-17 22:39:34,264 - DEBUG - Received username: admin, password length: 12
2025-02-17 22:39:34,264 - DEBUG - Attempting to establish database connection...
2025-02-17 22:39:34,264 - DEBUG - Database connection established successfully.
2025-02-17 22:39:34,455 - DEBUG - Incorrect password
2025-02-17 22:39:34,456 - INFO - 192.168.1.10 - - [17/Feb/2025 22:39:34] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:39:55,001 - DEBUG - Received username: admin, password length: 9
2025-02-17 22:39:55,001 - DEBUG - Attempting to establish database connection...
2025-02-17 22:39:55,001 - DEBUG - Database connection established successfully.
2025-02-17 22:39:55,191 - DEBUG - Login successful
2025-02-17 22:39:55,193 - INFO - 192.168.1.10 - - [17/Feb/2025 22:39:55] "POST /api/login HTTP/1.1" 200 -
2025-02-17 22:40:28,780 - INFO - 192.168.1.10 - - [17/Feb/2025 22:40:28] "GET / HTTP/1.1" 200 -
2025-02-17 22:40:37,534 - DEBUG - Received username: admin, password length: 11
2025-02-17 22:40:37,534 - DEBUG - Attempting to establish database connection...
2025-02-17 22:40:37,535 - DEBUG - Database connection established successfully.
2025-02-17 22:40:37,726 - DEBUG - Incorrect password
2025-02-17 22:40:37,727 - INFO - 192.168.1.10 - - [17/Feb/2025 22:40:37] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:41:45,110 - DEBUG - Received username: admin, password length: 14
2025-02-17 22:41:45,110 - DEBUG - Attempting to establish database connection...
2025-02-17 22:41:45,120 - DEBUG - Database connection established successfully.
2025-02-17 22:41:45,309 - DEBUG - Incorrect password
2025-02-17 22:41:45,310 - INFO - 192.168.1.10 - - [17/Feb/2025 22:41:45] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:41:52,476 - DEBUG - Received username: jkg, password length: 14
2025-02-17 22:41:52,476 - DEBUG - Attempting to establish database connection...
2025-02-17 22:41:52,476 - DEBUG - Database connection established successfully.
2025-02-17 22:41:52,478 - DEBUG - User not found
2025-02-17 22:41:52,667 - INFO - 192.168.1.10 - - [17/Feb/2025 22:41:52] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:42:03,585 - DEBUG - Received username: admin, password length: 14
2025-02-17 22:42:03,585 - DEBUG - Attempting to establish database connection...
2025-02-17 22:42:03,586 - DEBUG - Database connection established successfully.
2025-02-17 22:42:03,776 - DEBUG - Incorrect password
2025-02-17 22:42:03,777 - INFO - 192.168.1.10 - - [17/Feb/2025 22:42:03] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:45:49,108 - DEBUG - Received username: admin, password length: 14
2025-02-17 22:45:49,108 - DEBUG - Attempting to establish database connection...
2025-02-17 22:45:49,119 - DEBUG - Database connection established successfully.
2025-02-17 22:45:49,309 - DEBUG - Incorrect password
2025-02-17 22:45:49,310 - INFO - 192.168.1.10 - - [17/Feb/2025 22:45:49] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:45:59,781 - INFO - 192.168.1.10 - - [17/Feb/2025 22:45:59] "GET / HTTP/1.1" 200 -
2025-02-17 22:46:08,214 - DEBUG - Received username: admin, password length: 7
2025-02-17 22:46:08,214 - DEBUG - Attempting to establish database connection...
2025-02-17 22:46:08,214 - DEBUG - Database connection established successfully.
2025-02-17 22:46:08,406 - DEBUG - Incorrect password
2025-02-17 22:46:08,407 - INFO - 192.168.1.10 - - [17/Feb/2025 22:46:08] "[31m[1mPOST /api/login HTTP/1.1[0m" 401 -
2025-02-17 22:46:16,884 - DEBUG - Received username: admin, password length: 7
2025-02-17 22:46:16,884 - DEBUG - Attempting to establish database connection...
2025-02-17 22:46:16,885 - DEBUG - Database connection established successfully.
2025-02-17 22:46:16,886 - DEBUG - Account is locked
2025-02-17 22:46:16,887 - INFO - 192.168.1.10 - - [17/Feb/2025 22:46:16] "[31m[1mPOST /api/login HTTP/1.1[0m" 403 -
2025-02-17 22:46:23,770 - DEBUG - Received username: admin, password length: 7
2025-02-17 22:46:23,771 - DEBUG - Attempting to establish database connection...
2025-02-17 22:46:23,771 - DEBUG - Database connection established successfully.
2025-02-17 22:46:23,772 - DEBUG - Account is locked
2025-02-17 22:46:23,773 - INFO - 192.168.1.10 - - [17/Feb/2025 22:46:23] "[31m[1mPOST /api/login HTTP/1.1[0m" 403 -
2025-02-17 22:46:29,410 - DEBUG - Received username: admin, password length: 7
2025-02-17 22:46:29,410 - DEBUG - Attempting to establish database connection...
2025-02-17 22:46:29,410 - DEBUG - Database connection established successfully.
2025-02-17 22:46:29,411 - DEBUG - Account is locked
2025-02-17 22:46:29,412 - INFO - 192.168.1.10 - - [17/Feb/2025 22:46:29] "[31m[1mPOST /api/login HTTP/1.1[0m" 403 -
2025-02-17 22:46:35,045 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:46:35,045 - INFO - 192.168.1.10 - - [17/Feb/2025 22:46:35] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:46:46,777 - INFO - ratelimit 5 per 1 minute (192.168.1.10) exceeded at endpoint: login
2025-02-17 22:46:46,777 - INFO - 192.168.1.10 - - [17/Feb/2025 22:46:46] "[31m[1mPOST /api/login HTTP/1.1[0m" 429 -
2025-02-17 22:48:35,263 - INFO - 192.168.1.10 - - [17/Feb/2025 22:48:35] "GET / HTTP/1.1" 200 -
2025-02-17 22:57:35,415 - INFO - 192.168.1.19 - - [17/Feb/2025 22:57:35] "GET / HTTP/1.1" 200 -
2025-02-17 23:04:00,047 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 23:04:00,103 - INFO -  * Restarting with stat
2025-02-17 23:04:00,440 - INFO - Starting Flask server...
2025-02-17 23:04:00,510 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 23:04:00,510 - ERROR -   warnings.warn(
2025-02-17 23:04:00,527 - WARNING -  * Debugger is active!
2025-02-17 23:04:00,529 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 23:04:13,409 - INFO - Starting Flask server...
2025-02-17 23:04:13,480 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 23:04:13,481 - ERROR -   warnings.warn(
2025-02-17 23:04:13,483 - INFO - b" * Serving Flask app 'app'"
2025-02-17 23:04:13,483 - INFO - b' * Debug mode: on'
2025-02-17 23:04:13,508 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:443
 * Running on https://192.168.1.19:443
2025-02-17 23:04:13,508 - INFO - [33mPress CTRL+C to quit[0m
2025-02-17 23:04:13,509 - INFO -  * Restarting with stat
2025-02-17 23:04:13,766 - INFO - Starting Flask server...
2025-02-17 23:04:13,839 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 23:04:13,839 - ERROR -   warnings.warn(
2025-02-17 23:04:13,854 - WARNING -  * Debugger is active!
2025-02-17 23:04:13,857 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 23:04:25,803 - INFO - 192.168.1.19 - - [17/Feb/2025 23:04:25] "GET / HTTP/1.1" 200 -
2025-02-17 23:40:33,681 - INFO - 192.168.1.19 - - [17/Feb/2025 23:40:33] "GET / HTTP/1.1" 200 -
2025-02-17 23:40:43,727 - INFO - 192.168.1.10 - - [17/Feb/2025 23:40:43] "GET / HTTP/1.1" 200 -
2025-02-17 23:42:52,149 - INFO - 192.168.1.19 - - [17/Feb/2025 23:42:52] "GET / HTTP/1.1" 200 -
2025-02-17 23:43:02,191 - DEBUG - Received username: admin, password length: 9
2025-02-17 23:43:02,191 - DEBUG - Attempting to establish database connection...
2025-02-17 23:43:02,242 - DEBUG - Database connection established successfully.
2025-02-17 23:43:02,435 - DEBUG - Login successful
2025-02-17 23:43:02,436 - INFO - 192.168.1.19 - - [17/Feb/2025 23:43:02] "POST /api/login HTTP/1.1" 200 -
2025-02-17 23:43:22,434 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-17 23:43:22,470 - INFO -  * Restarting with stat
2025-02-17 23:43:22,769 - INFO - Starting Flask server...
2025-02-17 23:43:22,861 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 23:43:22,861 - ERROR -   warnings.warn(
2025-02-17 23:43:22,881 - WARNING -  * Debugger is active!
2025-02-17 23:43:22,884 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 23:43:45,259 - INFO - Starting Flask server...
2025-02-17 23:43:45,330 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 23:43:45,330 - ERROR -   warnings.warn(
2025-02-17 23:43:45,332 - INFO - b" * Serving Flask app 'app'"
2025-02-17 23:43:45,332 - INFO - b' * Debug mode: on'
2025-02-17 23:43:45,356 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:443
 * Running on https://192.168.1.19:443
2025-02-17 23:43:45,356 - INFO - [33mPress CTRL+C to quit[0m
2025-02-17 23:43:45,358 - INFO -  * Restarting with stat
2025-02-17 23:43:45,610 - INFO - Starting Flask server...
2025-02-17 23:43:45,681 - ERROR - C:\Users\proxmox102\AppData\Roaming\Python\Python313\site-packages\flask_limiter\extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
2025-02-17 23:43:45,681 - ERROR -   warnings.warn(
2025-02-17 23:43:45,696 - WARNING -  * Debugger is active!
2025-02-17 23:43:45,698 - INFO -  * Debugger PIN: 408-165-462
2025-02-17 23:43:54,727 - INFO - 192.168.1.19 - - [17/Feb/2025 23:43:54] "GET / HTTP/1.1" 200 -
2025-02-17 23:49:11,591 - INFO - 192.168.1.19 - - [17/Feb/2025 23:49:11] "GET / HTTP/1.1" 200 -
2025-02-17 23:49:13,411 - INFO - 192.168.1.19 - - [17/Feb/2025 23:49:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-02-17 23:49:46,865 - INFO - 192.168.1.19 - - [17/Feb/2025 23:49:46] "GET / HTTP/1.1" 200 -
2025-02-18 00:27:35,126 - INFO - 192.168.1.19 - - [18/Feb/2025 00:27:35] "GET / HTTP/1.1" 200 -
2025-02-18 00:28:45,994 - INFO - 192.168.1.19 - - [18/Feb/2025 00:28:45] "GET / HTTP/1.1" 200 -
2025-02-18 00:29:03,380 - INFO - 73.70.26.166 - - [18/Feb/2025 00:29:03] "GET / HTTP/1.1" 200 -
2025-02-18 00:29:03,552 - INFO - 73.70.26.166 - - [18/Feb/2025 00:29:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-02-18 00:29:09,346 - INFO - 103.203.59.1 - - [18/Feb/2025 00:29:09] "GET / HTTP/1.1" 200 -
2025-02-18 00:29:21,651 - INFO - 73.70.26.166 - - [18/Feb/2025 00:29:21] "GET / HTTP/1.1" 200 -
2025-02-18 00:29:22,312 - INFO - 73.70.26.166 - - [18/Feb/2025 00:29:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-02-18 00:29:59,011 - INFO - 192.168.1.10 - - [18/Feb/2025 00:29:59] "GET / HTTP/1.1" 200 -
2025-02-18 00:30:14,056 - INFO - 73.70.26.166 - - [18/Feb/2025 00:30:14] "GET / HTTP/1.1" 200 -
2025-02-18 00:30:36,315 - DEBUG - Received username: admin, password length: 9
2025-02-18 00:30:36,315 - DEBUG - Attempting to establish database connection...
2025-02-18 00:30:36,465 - DEBUG - Database connection established successfully.
2025-02-18 00:30:36,663 - DEBUG - Login successful
2025-02-18 00:30:36,665 - INFO - 73.70.26.166 - - [18/Feb/2025 00:30:36] "POST /api/login HTTP/1.1" 200 -
2025-02-18 00:30:42,877 - INFO - 73.70.26.166 - - [18/Feb/2025 00:30:42] "[33mPOST /proxmox-api/api2/json/nodes/prxmxhomesrvr/qemu/104/vncproxy HTTP/1.1[0m" 404 -
2025-02-18 00:52:42,972 - INFO - 133.242.174.119 - - [18/Feb/2025 00:52:42] "[33mGET /robots.txt HTTP/1.1[0m" 404 -
2025-02-18 00:52:43,471 - INFO - 133.242.174.119 - - [18/Feb/2025 00:52:43] "GET / HTTP/1.1" 200 -
2025-02-18 00:52:55,694 - INFO -  * Detected change in 'C:\\Dev\\Web Apps\\VM_WEB_GUI\\app.py', reloading
2025-02-18 00:52:55,754 - INFO -  * Restarting with stat
